### ISSUE TITLE
`@log` decorator causes Exception when used with `--workers` command line argument

### ISSUE THREAD

**Issue by ast0815** [riga/law#58]
Hello,

I am currently trying to set up my analysis with luigi and law. I stumbled over this strange error:

When I decorate one of my task's methods with `@log` and then call `law` with the `--workers 2` flag, the some jobs fail with the error message below:

```
Runtime error:
Traceback (most recent call last):
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 86, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 136, in safe_output
    return fn(task, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/t2kframework.py", line 212, in run
    self.create_and_run_script()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 86, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 121, in log
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 18: ordinal not in range(128)
```

I have not yet figured out whether there is any pattern in the jobs that fail/succeed, but at least the first jobs to be started on the workers tend to be ok. The error never appears with just a single worker. A least it did not so far.

**Comment by riga** [comment]
First of all, there is a difference when using `--workers >1`. Luigi will use sub processes to execute the tasks' run methods which might be a reason why you don't see this for 1 worker. `--worker-force-multiprocessing --workers 1` should lead to the same error.

But 2 workers and no log decorator is fine?
I just fixed the error re-raising in the log decorator. Can you try again with the latest master so we can see where the unicode error emerges.

--
Fyi: [Here](https://gitlab.cern.ch/aachen-3a-cms/jet-tagging-sf) is also one example how we use law in an analysis.

**Comment by ast0815** [comment]
Ok, so with the master branch version of law, I get this error message:

```
Traceback (most recent call last):
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 124, in log
    ret = fn(task, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/t2kframework.py", line 192, in create_and_run_script
    print_(line, end='')
  File "/home/ppd/kdf77245/.law/software/six.py", line 801, in print_
    _print(*args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 809, in write
    self._write(*args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 865, in _write
    consumer.write(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 18: ordinal not in range(128)
```

The command I am running does produce non-ascii characters, but so far that has never been a problem and all `print` or `print_` calls worked just fine. And the output of the commands does not change depending on the number of workers I use.

My luigi/law does not seem to support the `--worker-force-multiprocessing` flag.

Thanks for the link to the jet analysis. I will use that for inspiration. :)

**Comment by ast0815** [comment]
Oh, and having multiple instances of `law run Whatever` at the same time, works just as well. It is only with the `--workers >1` flag that I see this problem.

**Comment by riga** [comment]
This should work now, could you give it another try?

**Comment by ast0815** [comment]
That seems to have changed nothing. I still get the same error.

**Comment by ast0815** [comment]
I created a gist with a minimal example that yields the same error message for me:

https://gist.github.com/ast0815/5ff9b2e8f17915c2e2b715e2bbdc1544

Interestingly, this one also fails in single-worker mode. It works without problem when removing the `@log` decorator.

**Comment by riga** [comment]
Thanks. Turned out to be - of course - a py2 thing as file objects behave quite differently regarding encoding w.r.t. py3. `sys.stdout` on the other hand does not, which caused some confusion.
The last commit should have fixed it. Can you try one last time?

**Comment by ast0815** [comment]
When I run the minimal example now, I get this error:

```
Traceback (most recent call last):
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 92, in wrapper
    return decorator(fn, _opts, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/decorator.py", line 124, in log
    ret = fn(task, *args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/bug.py", line 18, in run
    print u"Motörhead"
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 833, in write
    self._write(*args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 895, in _write
    consumer.write(*args, **kwargs)
  File "/opt/ppd/scratch/kdf77245/t2k_software/gasInteractions/gas_interaction_analysis/law/ENV27/lib/python2.7/site-packages/law/util.py", line 797, in write
    return write_orig(six.u(data), *args, **kwargs)
  File "/home/ppd/kdf77245/.law/software/six.py", line 653, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
```

**Comment by riga** [comment]
Ok, my mistake with `six.u()`. Your example works for me now (after removing the `sh` import) with

```shell
> LAW_LOG_LEVEL=DEBUG law run bug.Test --local-scheduler --workers 2
```

**Comment by ast0815** [comment]
That seems to have done the trick. Thanks!

**Comment by riga** [comment]
Finally =)
Thanks for reporting this!
